services:

  - type: web
    name: school-inventory-app
    env: java
    plan: free

    repo: https://github.com/TuanAnh-AKA/Quan_Ly_Kho_Truong_Hoc.git
    branch: main

    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/quan_ly_kho-0.0.1-SNAPSHOT.jar

